// @slicedlabs/tokens — generator.
// Reads tokens.toml (product SSOT) and emits:
//   dist/tokens.css  — :root (dark) + [data-temp="warm"] (cream) custom properties
//   dist/p3.css      — Display-P3 wide-gamut brand overrides
//   dist/tokens.js   — the same values as JS (for R3F / Mapbox / OG / Spline)
// Bun parses .toml natively. Run: `bun run src/build.ts`.
import tokens from "../tokens.toml";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

type Dict = Record<string, string>;
const t = tokens as Record<string, any>;

const root = dirname(dirname(fileURLToPath(import.meta.url))); // packages/tokens
const dist = join(root, "dist");
mkdirSync(dist, { recursive: true });

const GEN = "/* GENERATED by @slicedlabs/tokens from tokens.toml — do not edit by hand. */";

// emit `--key: value;` lines (indent 2). Optional name prefix (fonts → --font-*).
const vars = (obj: Dict, prefix = "") =>
  Object.entries(obj)
    .map(([k, v]) => `  --${prefix}${k}: ${v};`)
    .join("\n");

// ── tokens.css ────────────────────────────────────────────────────────────────
const darkRoot = [
  vars(t.color.dark),
  "",
  vars(t.brand),
  `  --blend: ${t.blend.value};`,
  "",
  vars(t.section),
  "",
  vars(t.status),
  "",
  vars(t.material),
  "",
  vars(t.glass),
  "",
  vars(t.motion),
  "",
  vars(t.font, "font-"),
  "",
  vars(t.scale),
  "",
  "  color-scheme: dark;",
].join("\n");

const warmRoot = [vars(t.color.warm), "  color-scheme: light;"].join("\n");

const tokensCss = `${GEN}

/* DARK / PREMIUM (default — company / build-in-public) */
:root {
${darkRoot}
}

/* WARM / FOOD (truck · menu · consumer) — cream is law */
[data-temp="warm"] {
${warmRoot}
}
`;

// ── p3.css ──────────────────────────────────────────────────────────────────
const p3Vars = Object.entries(t.brand_p3 as Dict)
  .map(([k, v]) => `      --${k}: ${v};`)
  .join("\n");

const p3Css = `${GEN}

/* sRGB in tokens.css is the fallback; these override only where the display can show them. */
@supports (color: color(display-p3 1 1 1)) {
  @media (color-gamut: p3) {
    :root {
${p3Vars}
    }
  }
}
`;

// ── tokens.js ─────────────────────────────────────────────────────────────────
const j = (o: unknown) => JSON.stringify(o, null, 2);
const tokensJs = `// GENERATED by @slicedlabs/tokens from tokens.toml — do not edit by hand.
export const brand = ${j(t.brand)};
export const brandP3 = ${j(t.brand_p3)};
export const dark = ${j(t.color.dark)};
export const warm = ${j(t.color.warm)};
export const status = ${j(t.status)};
export const scale = ${j(t.scale)};
export const motion = ${j(t.motion)};
export default { brand, brandP3, dark, warm, status, scale, motion };
`;

writeFileSync(join(dist, "tokens.css"), tokensCss);
writeFileSync(join(dist, "p3.css"), p3Css);
writeFileSync(join(dist, "tokens.js"), tokensJs);

console.log("@slicedlabs/tokens → dist/{tokens.css, p3.css, tokens.js}");
